plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = "baity-v${project.mod_version}-${project.minecraft_version_label}mc"
}

repositories {
    mavenCentral()
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
    maven {
        name = 'TerraformersMC'
        url = 'https://maven.terraformersmc.com/releases'
    }
    maven {
        name = 'JitPack'
        url = 'https://jitpack.io'
    }
    maven {
        name = 'Hypixel'
        url = 'https://repo.hypixel.net/repository/Hypixel'
        content {
            includeGroupAndSubgroups 'net.hypixel'
        }
    }
}

loom {
    accessWidenerPath = file("src/main/resources/baity.classtweaker")
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.4.1")))

    compileOnly("com.terraformersmc:modmenu:20.0.1") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    localRuntime("com.terraformersmc:modmenu:20.0.1") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    compileOnly "net.hypixel:mod-api:${project.hypixel_mod_api_version}"

    testImplementation platform("org.junit:junit-bom:5.11.4")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

processResources {
    def replaceProperties = [
            version           : project.version,
            minecraft_version : project.minecraft_version,
            loader_version    : project.loader_version,
    ]
    inputs.properties replaceProperties
    filteringCharset = "UTF-8"

    filesMatching("fabric.mod.json") {
        expand replaceProperties
    }
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = targetJavaVersion
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

tasks.named("test") {
    useJUnitPlatform()
}

jar {
    from("LICENSE") {
        rename { "${it}_baity"}
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(AbstractArchiveTask).configureEach {
    archiveVersion.set("")
}
