# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.1
loader_version=0.18.1

# Mod Properties
mod_version=1.2.7
maven_group=com.shyeuar
archives_base_name=baity

# Dependencies
fabric_version=0.138.3+1.21.10

