# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
# Fabric Properties - Minecraft 26.2
minecraft_version=26.2
minecraft_version_label=26.2
loader_version=0.19.3
loom_version=1.17.17

# Mod Properties
mod_version=1.7.0
maven_group=com.shyeuar
archives_base_name=baity

# Dependencies
fabric_api_version=0.157.0+26.2
hypixel_mod_api_version=1.0.2
